project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    tools:
      - icon: github
        href: https://github.com/AnonymousVikram/E155-Portfolio
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
        - text: Overview
          href: labs/lab_overview.qmd
        - text: Lab 1
          href: labs/lab1/lab1.qmd
        - text: Lab 2
          href: labs/lab2/lab2.qmd
        - text: Lab 3
          href: labs/lab3/lab3.qmd
        - text: Lab 4
          href: labs/lab4/lab4.qmd
      - href: blog.qmd
        text: Blog
      - text: Resources
        href: resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



