project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    tools:
      - icon: github
      - href: https://github.com/AnonymousVikram
    left:
      - href: home.qmd
        text: Home
      - text: Labs
        menu:
        - text: Lab 1
          href: labs/lab1/lab1.qmd
      - href: blog.qmd
        text: Blog
      - text: Resources
        href: resrouces.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true



