---
title: "Labs Overview"
---

## Background

The Microprocessor Systems class at Harvey Mudd employs a lab-based approach to testing absorption of material. As a result of this, there are seven labs covering a wide variety of topics, each of which has clear guidelines and a report. Below, links can be found to the original task and the corresponding write-up for my submission.

## Labs
| Lab Number | Instructions | Report | Github Repo |
| :---: | :---: | :---: | :---: |
| 1: FPGA and MCU Setup and Testing | [Lab 1 Instructions](https://hmc-e155.github.io/lab/lab1/) | [Lab 1 Report](lab1/lab1.qmd) | [Lab 1 Repo](https://github.com/AnonymousVikram/e155-lab1) |
| 2: Multiplexed 7-Segment Display | [Lab 2 Instructions](https://hmc-e155.github.io/lab/lab2/) | [Lab 2 Report](lab2/lab2.qmd) | [Lab 2 Repo](https://github.com/AnonymousVikram/e155-lab2) |
| 3: Keypad Scanner | [Lab 3 Instructions](https://hmc-e155.github.io/lab/lab3/) | [Lab 3 Report](lab3/lab3.qmd) | [Lab 3 Repo](https://github.com/AnonymousVikram/e155-lab3) |
| 4: Digital Audio | [Lab 4 Instructions](https://hmc-e155.github.io/lab/lab4/) | [Lab 4 Report](lab4/lab4.qmd) | [Lab 4 Repo](https://github.com/AnonymousVikram/e155-lab4) |
| 5: Interrupts | [Lab 5 Instructions](https://hmc-e155.github.io/lab/lab5/) | [Lab 5 Report](lab5/lab5.qmd) | [Lab 5 Repo](https://github.com/AnonymousVikram/e155-lab5) |
| 6: The Internet of Things and SPI | [Lab 6 Instructions](https://hmc-e155.github.io/lab/lab6/) | [Lab 6 Report](lab6/lab6.qmd) | [Lab 6 Repo](https://github.com/AnonymousVikram/e155-lab6) |